ssh nn1 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh nn2 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh dn1 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh dn2 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh dn3 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh dn4 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent stop"
ssh nn1 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-server stop"
