ssh nn1 "/opt/cm-5.13.0/etc/init.d/cloudera-scm-server start"
ssh nn1  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
ssh nn2  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
ssh dn1  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
ssh dn2  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
ssh dn3  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
ssh dn4  "/opt/cm-5.13.0/etc/init.d/cloudera-scm-agent start"
